In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[11, 21]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[22, 16], [11, 21], [28, 29], [20, 24, 4], [3, 29, 9], [3, 16], [6, 29, 2], [7, 14], [7, 29], [16, 29]]


In [4]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[22 16  0]
 [11 21  0]
 [28 29  0]
 [20 24  4]
 [ 3 29  9]
 [ 3 16  0]
 [ 6 29  2]
 [ 7 14  0]
 [ 7 29  0]
 [16 29  0]]


In [5]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model.fit(X, y, epochs=50, verbose=0)

In [10]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 117ms/step - loss: 0.6268 - accuracy: 1.0000


1.0

In [18]:
weights = model.get_layer('embedding').get_weights()[0]
weights


array([[ 0.06885232, -0.01106692, -0.06994578, -0.01025304],
       [-0.01837505,  0.04158317,  0.04448858,  0.00698918],
       [ 0.04965889, -0.04171439, -0.07151355, -0.00318159],
       [ 0.02116635, -0.01369729, -0.01296804,  0.00978241],
       [-0.07469328,  0.0998361 ,  0.03259601,  0.09611519],
       [-0.0250455 ,  0.03077556,  0.02922552,  0.01568221],
       [ 0.08493208,  0.01008808, -0.07394355, -0.03955924],
       [ 0.01054302,  0.02699385, -0.04467751, -0.04684579],
       [ 0.04756114,  0.04600174,  0.0335398 ,  0.03625501],
       [-0.07780313,  0.05832656,  0.08672373,  0.03536027],
       [ 0.03883237,  0.00759583,  0.03467331,  0.0459266 ],
       [-0.05989338, -0.03059751,  0.03401687,  0.00451967],
       [-0.03683208, -0.03173459, -0.01741862,  0.00261777],
       [ 0.04060921, -0.01889566,  0.00034707, -0.01699131],
       [-0.07601276, -0.04964753, -0.07258041, -0.01696463],
       [-0.00317914, -0.02842761, -0.00929571,  0.01289442],
       [ 0.05190332,  0.

In [19]:
weights[22]

array([-0.07259389, -0.06743771,  0.07530884,  0.09123471], dtype=float32)

In [20]:
weights[11]

array([-0.05989338, -0.03059751,  0.03401687,  0.00451967], dtype=float32)