In [ ]:
!pip install bing_image_downloader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
mkdir images

In [ ]:
from bing_image_downloader import downloader
downloader.download('apple fruit', limit = 100, output_dir = 'images')

Streaming output truncated to the last 5000 lines.



[!!]Indexing page: 35

[%] Indexed 9 Images on Page 35.




[!!]Indexing page: 36

[%] Indexed 9 Images on Page 36.




[!!]Indexing page: 37

[%] Indexed 9 Images on Page 37.




[!!]Indexing page: 38

[%] Indexed 9 Images on Page 38.




[!!]Indexing page: 39

[%] Indexed 9 Images on Page 39.




[!!]Indexing page: 40

[%] Indexed 9 Images on Page 40.




[!!]Indexing page: 41

[%] Indexed 9 Images on Page 41.




[!!]Indexing page: 42

[%] Indexed 9 Images on Page 42.




[!!]Indexing page: 43

[%] Indexed 9 Images on Page 43.




[!!]Indexing page: 44

[%] Indexed 9 Images on Page 44.




[!!]Indexing page: 45

[%] Indexed 9 Images on Page 45.




[!!]Indexing page: 46

[%] Indexed 9 Images on Page 46.




[!!]Indexing page: 47

[%] Indexed 9 Images on Page 47.




[!!]Indexing page: 48

[%] Indexed 9 Images on Page 48.




[!!]Indexing page: 49

[%] Indexed 9 Images on Page 49.




[!!]Indexing page: 50

[%] Indexed 9 Images on

In [ ]:
from bing_image_downloader import downloader
downloader.download('mango', limit = 100, output_dir = 'images')

Streaming output truncated to the last 5000 lines.




[!!]Indexing page: 98

[%] Indexed 9 Images on Page 98.




[!!]Indexing page: 99

[%] Indexed 9 Images on Page 99.




[!!]Indexing page: 100

[%] Indexed 9 Images on Page 100.




[!!]Indexing page: 101

[%] Indexed 10 Images on Page 101.




[!!]Indexing page: 102

[%] Indexed 9 Images on Page 102.




[!!]Indexing page: 103

[%] Indexed 10 Images on Page 103.




[!!]Indexing page: 104

[%] Indexed 9 Images on Page 104.




[!!]Indexing page: 105

[%] Indexed 9 Images on Page 105.




[!!]Indexing page: 106

[%] Indexed 9 Images on Page 106.




[!!]Indexing page: 107

[%] Indexed 10 Images on Page 107.




[!!]Indexing page: 108

[%] Indexed 9 Images on Page 108.




[!!]Indexing page: 109

[%] Indexed 9 Images on Page 109.


[%] Downloading Image #65 from https://mangostudio.pl/wp-content/uploads/2016/06/Mango-Studio-Projektowanie-wnętrz-pod-klucz-dom-loftowy-kolonialny-nowoczesny-salon-kominek-koza20-683x1024.jpg
[!] Issue g

In [ ]:
import tensorflow as tf

In [ ]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [ ]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [ ]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [ ]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [ ]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [ ]:
tf_dataset = tf_dataset.map(lambda x: x * 50)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1050
1100
1550
1600
1700
1550


In [ ]:
tf_dataset = tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1050
1100
1550
1550
1700
1600


In [ ]:
for sales_batch in tf_dataset.batch(3):
    print(sales_batch.numpy())

[1050 1550 1550]
[1100 1600 1700]


In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*50).shuffle(3).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1550 1600]
[1700 1550]
[1100 1050]


In [ ]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle = False)
for file in images_ds.take(5):
    print(file.numpy())

b'images/apple fruit/Image_1.jpg'
b'images/apple fruit/Image_10.jpg'
b'images/apple fruit/Image_100.jpg'
b'images/apple fruit/Image_11.jpg'
b'images/apple fruit/Image_12.png'


In [ ]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(4):
    print(file.numpy())

b'images/apple fruit/Image_82.jpg'
b'images/mango/Image_4.jpg'
b'images/mango/Image_91.jpg'
b'images/mango/Image_66.jpg'


In [ ]:
image_count = len(images_ds)
print(image_count)

200


In [ ]:
class_names = ["apple fruit", "mango"]

In [ ]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [ ]:
print(len(train_ds))
print(len(test_ds))


160
40


In [ ]:
def process_image(file_path):
  label = get_label(file_path)
  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img, [128,128])
  return img, label

In [ ]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[1]

In [ ]:
get_label('images/mango/Image_60.jpg')

<tf.Tensor: shape=(), dtype=string, numpy=b'mango'>

In [ ]:
get_label("images/mango/Image_77.jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'mango'>

In [ ]:
process_image('images/apple fruit/Image_100.jpg')

(<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
 array([[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],
 
        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],
 
        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],
 
        ...,
 
        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],
 
        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
      

In [ ]:
p = 'images/mango/Image_90.jpg'
p.split('/')[1]

'mango'

In [ ]:
train_ds = train_ds.map(process_image)

for img, label in train_ds.take(1):
  print('Img***:',img)
  print('Label***:',label)

Img***: tf.Tensor(
[[[  9.         9.         9.      ]
  [  9.         9.         9.      ]
  [  9.         9.         9.      ]
  ...
  [ 14.        14.        14.      ]
  [ 14.        14.        14.      ]
  [ 14.        14.        14.      ]]

 [[  9.         9.         9.      ]
  [  9.         9.         9.      ]
  [  9.         9.         9.      ]
  ...
  [ 14.        14.        14.      ]
  [ 14.        14.        14.      ]
  [ 14.        14.        14.      ]]

 [[  9.         9.         9.      ]
  [  9.         9.         9.      ]
  [  9.         9.         9.      ]
  ...
  [ 13.        13.        13.      ]
  [ 13.        13.        13.      ]
  [ 13.        13.        13.      ]]

 ...

 [[ 79.25659   37.31909   23.358154]
  [ 77.21118   31.25      14.8125  ]
  [ 72.08179   33.71289   12.533203]
  ...
  [151.91357   89.851074  38.723877]
  [143.74658   88.61377   40.614502]
  [147.61938   93.244385  45.931885]]

 [[129.625     76.75      29.75    ]
  [129.80249   76.

In [ ]:
def scale(image, label):
    return image/255, label

In [ ]:
train_ds = train_ds.map(scale)


In [ ]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [74.74609  17.746094 34.746094]
****Label:  b'mango'
****Image:  [225.6347 218.6347 225.6347]
****Label:  b'apple fruit'
****Image:  [120.78906 103.63867  91.91211]
****Label:  b'mango'
****Image:  [255. 255. 255.]
****Label:  b'mango'
****Image:  [20.992188  48.089844   5.1171875]
****Label:  b'apple fruit'
